title: Lisyn - Collaborative Playlist

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Create the interactive playlist live and listen to music together. Set your vibe by adding songs to the playlist, vote for songs shared by friends to move them up in the queue.

# Theme
theme: minima

minima:
# Links
  social_links:
    - { platform: twitter, user_url: "https://twitter.com/lisyn_app" }

# App links
include: [".well-known"]
